### PR TITLE
Documentation revision

### PR DESCRIPTION
**Pull request by Jaja0624**
- Adds separate dependencies section with links
- Revised Setup section to be more intuitive for people new to node.js

### CODE REVIEW

**Comment by Jaja0624** [comment]
@allisonchanykei

**Review by allisonchanykei — APPROVED** [review]
Squash your commits into one please

**Comment by Jaja0624** [comment]
> Squash your commits into one please

Just did this please review thx

**Comment by allisonchanykei** [comment]
it was already approved... but can u just squash into 1 commit - "Updated documentation"

**Comment by allisonchanykei** [comment]
but can u just squash into 1 commit - "Updated documentation"

**Pull request merged**
